/**
 * Generates the boilerplate code for a main Express + Mongoose server file.
 * @returns A string containing the TypeScript code for the main server setup.
 */

export const appBoilerplate = (): string => {
  const lines: string[] = [
    `import dotenv from 'dotenv'`,
    `dotenv.config()`,
    ``,
    `const { MONGO_URL, DB, CLIENT,  PORT} = process.env`,
    ``,
    `import mongoose from 'mongoose'`,
    `mongoose.connect(\`\${MONGO_URL}/\${DB}\`)`,
    ``,
    `.then(() => console.log(\`Database connected - \${DB}\`))`,
    ``,
    `.catch(() => {`,
    `  console.log(\`Database connection failed - \${DB}\`)`,
    `})`,
    ``,
    `import express, { Request, Response } from 'express'`,
    `import morgan from 'morgan'`,
    `import cors from 'cors'`,
    `import cookieParser from 'cookie-parser'`,
    `import helmet from "helmet"`,
    `import rateLimit from "express-rate-limit"`,
    ``,
    `import AuthRouter from './router/auth.router'`,
    `import homePageHtml from './view/homePage.html'`,
    ``,
    `const app = express()`,
    `app.listen(PORT, () => console.log(\`Server is running on http://localhost:\${PORT}\`))`,
    ``,
    `app.use(cors({`,
    `  origin: \`\${CLIENT}\`,`,
    `  credentials: true`,
    `}))`,
    ``,
    `app.use(helmet())`,
    `app.use(cookieParser())`,
    `app.use(express.json())`,
    `app.use(express.urlencoded({ extended: false }))`,
    `app.use(morgan('dev'))`,
    ``,
    `app.use(rateLimit({`,
    `  windowMs: 15 * 60 * 1000,`,
    `  max: 100,`,
    `  message: "Too many requests"`,
    `}))`,
    ``,
    `app.get("/", (req: Request, res: Response) => {`,
    `  res.setHeader('Content-Type', 'text/html')`,
    `  res.send(homePageHtml())`,
    `})`,
    ``,
    `app.use('/auth', AuthRouter)`,
    ``,
    `app.use((req: Request, res: Response) => {`,
    `  res.status(404).json({ message: \`API endpoint - \${req.url} not found\` })`,
    `})`
  ];

  return lines.join('\n');
};
