export const authMiddlewareBoilerplate = () => {
  return [
    `import { NextFunction, Response } from "express"`,
    `import { CatchError, TryError } from "../lib/error"`,
    `import jwt, { JwtPayload } from "jsonwebtoken"`,
    `import { SessionInterface, SessionRequestInterface } from "../interface/auth.interface"`,
    ``,
    `const AuthMiddleware = async (req: SessionRequestInterface, res: Response, next: NextFunction) => {`,
    `\ttry {`,
    `\t\tconst accessToken = req.cookies?.accessToken`,
    ``,
    `\t\tif (!accessToken)`,
    `\t\t\tthrow TryError("Unauthorized.", 401)`,
    ``,
    `\t\tif (!process.env.JWT_SECRET)`,
    `\t\t\tthrow TryError("Server misconfiguration: JWT secret missing.", 500)`,
    ``,
    `\t\tlet user: JwtPayload`,
    `\t\ttry {`,
    `\t\t\tuser = jwt.verify(accessToken, process.env.JWT_SECRET as string) as JwtPayload`,
    `\t\t} catch {`,
    `\t\t\tthrow TryError("Invalid or expired token.", 403)`,
    `\t\t}`,
    ``,
    `\t\tif (!user.id || !user.email)`,
    `\t\t\tthrow TryError("Invalid token payload.", 400)`,
    ``,
    `\t\tconst session: SessionInterface = {`,
    `\t\t\tid: user.id,`,
    `\t\t\tfullname: user.fullname,`,
    `\t\t\temail: user.email,`,
    `\t\t\tmobile: user.mobile,`,
    `\t\t}`,
    ``,
    `\t\treq.session = session`,
    `\t\tnext()`,
    `\t} catch (err) {`,
    `\t\tCatchError(res, err, "Failed to authenticate.")`,
    `\t}`,
    `}`,
    ``,
    `export default AuthMiddleware`
  ].join("\n")
}
