export const authControllerBoilerplate = (): string => {
  
  const lines: string[] = [
    'import { CookieOptions, Request, Response } from "express";',
    "import bcrypt from 'bcrypt'",
    "import jwt from 'jsonwebtoken'",
    "import {v4 as uuid} from 'uuid'",
    'import moment from "moment";',
    '',
    'import AuthModel from "../model/auth.model";',
    'import { CatchError, TryError } from "../lib/error";',
    'import { SessionInterface, SessionRequestInterface } from "../interface/auth.interface";',
    '',
    'const {NODE_ENV, DOMAIN, JWT_SECRET} = process.env',
    "const accessTokenExpiryTime = '10m'",
    'const accessTokenExpiryTimeInMS = (10*60*1000)',
    'const refreshTokenExpiryTimeInMS = (7*24*60*60*1000)',
    '',
    'const generateTokens = (payload: SessionInterface) => {',
    '\tconst accessToken = jwt.sign(payload, JWT_SECRET as string, {expiresIn: accessTokenExpiryTime})',
    '\tconst refreshToken = uuid()',
    '\treturn {accessToken, refreshToken}',
    '}',
    '',
    'const getCookieOption = (cookieType: "refresh" | "access"): CookieOptions=>{',
    '\treturn {',
    '\t\thttpOnly: true,',
    "\t\tsecure: NODE_ENV === 'dev' ? false : true,",
    '\t\tmaxAge: cookieType === \'access\' ? accessTokenExpiryTimeInMS : refreshTokenExpiryTimeInMS,',
    '\t\tdomain: DOMAIN as string,',
    "\t\tsameSite: 'lax'",
    '\t}',
    '}',
    '',
    'const setCookies = async (res:Response, payload:SessionInterface) => {',
    '\tconst {accessToken, refreshToken} = generateTokens(payload)',
    '',
    '\tawait AuthModel.updateOne({_id: payload.id}, {$set: {',
    "\t\trefreshToken,",
    "\t\texpiry: moment().add(7, 'days').toDate()",
    '\t}})',
    '',
    "\tres.cookie('accessToken', accessToken, getCookieOption('access'))",
    "\tres.cookie('refreshToken', refreshToken, getCookieOption('refresh'))",
    '}',
    '',
    'export const signup = async (req:Request, res:Response) => {',
    '\ttry {',
    '\t\tawait AuthModel.create(req.body)',
    '\t\tres.status(201).json({message: "Signup success."})',
    '\t} catch (err) {',
    '\t\tCatchError(res, err, "Failed to Signup, please try later.")',
    '\t}',
    '}',
    '',
    'export const login = async (req:Request, res:Response) => {',
    '\ttry {',
    '\t\tconst email = req.body?.email',
    '\t\tconst password = req.body?.password',
    '',
    '\t\tif(!email || !password)',
    '\t\t\tthrow TryError("Both email and password required.", 403)',
    '',
    '\t\tconst user = await AuthModel.findOne({email})',
    '',
    '\t\tif(!user)',
    '\t\t\tthrow TryError("User not found", 404)',
    '',
    '\t\tconst isLogin = await bcrypt.compare(password, user.password)',
    '',
    '\t\tif(!isLogin)',
    '\t\t\tthrow TryError("Invalid credentials", 401)',
    '',
    '\t\tconst payload = {',
    '\t\t\tid : user._id,',
    '\t\t\tfullname : user.fullname,',
    '\t\t\temail : user.email,',
    '\t\t\tmobile : user.mobile,',
    '\t\t}',
    '',
    '\t\tawait setCookies(res, payload)',
    '',
    '\t\tres.json({message: "Login success."})',
    '\t} catch (err) {',
    '\t\tCatchError(res, err, "Failed to Login, please try later.")',
    '\t}',
    '}',
    '',
    'export const refreshToken = async (req:SessionRequestInterface, res:Response) => {',
    '\ttry {',
    '\t\tconst session = req?.session',
    '',
    '\t\tif(!session)',
    '\t\t\tthrow TryError("unauthorized.", 401)',
    '',
    '\t\tawait setCookies(res, session)',
    '',
    '\t\tres.json({message: "Token refreshed successfully."})',
    '\t} catch (err) {',
    '\t\tCatchError(res, err, "Failed to refresh tokens, please try later.")',
    '\t}',
    '}',
  ]
  
  return lines.join('\n')
}
