export const authModelBoilerplate = (): string => {
  
  const lines: string[] = [
    'import { model, Schema } from "mongoose";',
    "import bcrypt from 'bcrypt'",
    '',
    'const authSchema = new Schema({',
    '\tfullname:{',
    '\t\ttype: String,',
    '\t\ttrim: true,',
    '\t\tlowercase: true,',
    '\t\trequired: true,',
    '\t},',
    '\temail:{',
    '\t\ttype: String,',
    '\t\ttrim: true,',
    '\t\tunique: true,',
    '\t\trequired: true,',
    '\t},',
    '\tmobile:{',
    '\t\ttype: String,',
    '\t\ttrim: true,',
    '\t\tunique: true,',
    '\t\trequired: true,',
    '\t},',
    '\timage:{',
    '\t\ttype: String,',
    '\t\tdefault: null,',
    '\t},',
    '\tpassword:{',
    '\t\ttype: String,',
    '\t\ttrim: true,',
    '\t\trequired: true,',
    '\t},',
    '\trefreshToken:{',
    '\t\ttype: String,',
    '\t},',
    '\texpiry:{',
    '\t\ttype: Date,',
    '\t},',
    '},{timestamps: true})',
    '',
    "authSchema.pre('save', async function (next) {",
    '\tthis.refreshToken = null',
    '\tthis.expiry = null',
    '\tif(!this.isModified("password") return next()',
    '\t\tthis.password = await bcrypt.hash(this.password.toString(), 12)',
    '\tnext()',
    '})',
    '',
    'const AuthModel = model("Auth", authSchema)',
    '',
    'export default AuthModel',
  ]
  
  return lines.join('\n')
}
