export const gitignoreBoilerplate = ()=>{
const lines: string[] = [
  '# Node.js',
  'node_modules/',
  'npm-debug.log*',
  'yarn-debug.log*',
  'yarn-error.log*',
  'pnpm-debug.log*',
  '',
  '# Environment variables',
  '.env',
  '',
  '# Logs',
  'logs/',
  '*.log',
  'npm-debug.log*',
  'yarn-debug.log*',
  'lerna-debug.log*',
  '',
  '# OS files',
  '.DS_Store',
  'Thumbs.db',
  '',
  '# TypeScript',
  'dist/',
  'build/',
  '*.tsbuildinfo',
  '',
  '# Optional npm cache directory',
  '.npm',
  '',
  '# Optional eslint cache',
  '.eslintcache',
  '',
  '# Optional IDE / Editor files',
  '.vscode/',
  '.idea/',
  '*.sublime-project',
  '*.sublime-workspace',
  '',
  '# Optional Mac files',
  '*.DS_Store',
  '',
  '# Optional coverage directory',
  'coverage/',
  '',
  '# Optional temp files',
  'tmp/',
  'temp/'
]
return lines.join("\n")
}
