export const homePageHtml = (): string => {
  const lines: string[] = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    '  <title>🙏🏻 Shree Dnyanoba Mauli Tukaram ⛳</title>',
    '  <style>',
    '    :root {',
    '      --bg: #0f172a;',
    '      --card: #111827;',
    '      --text: #e5e7eb;',
    '      --muted: #94a3b8;',
    '      --accent: #f59e0b;',
    '      --accent-2: #10b981;',
    '      --border: #1f2937;',
    '    }',
    '    * { box-sizing: border-box; margin: 0; padding: 0; }',
    '    body {',
    '      font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Apple Color Emoji", "Segoe UI Emoji";',
    '      background: radial-gradient(1200px 800px at 10% -10%, #1e293b 0%, var(--bg) 60%),',
    '                  radial-gradient(1000px 600px at 110% 10%, #0b1220 0%, var(--bg) 70%);',
    '      color: var(--text);',
    '      min-height: 100vh;',
    '      display: grid;',
    '      place-items: center;',
    '      padding: 24px;',
    '      line-height: 1.5;',
    '    }',
    '    .card {',
    '      width: 100%;',
    '      max-width: 520px;',
    '      background: linear-gradient(180deg, rgba(255,255,255,0.03), rgba(255,255,255,0.01));',
    '      border: 1px solid var(--border);',
    '      border-radius: 20px;',
    '      padding: 28px 24px 24px;',
    '      box-shadow: 0 20px 50px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.04);',
    '      backdrop-filter: blur(8px);',
    '    }',
    '    .header {',
    '      text-align: center;',
    '      margin-bottom: 18px;',
    '    }',
    '    h1 {',
    '      font-size: clamp(20px, 4.5vw, 28px);',
    '      font-weight: 800;',
    '      letter-spacing: -0.02em;',
    '      background: linear-gradient(90deg, #fbbf24, #f59e0b 45%, #f97316);',
    '      -webkit-background-clip: text;',
    '      background-clip: text;',
    '      color: transparent;',
    '      text-shadow: 0 10px 30px rgba(245, 158, 11, 0.25);',
    '    }',
    '    .subtitle {',
    '      font-size: 13px;',
    '      color: var(--muted);',
    '      margin-top: 6px;',
    '    }',
    '    .links {',
    '      display: grid;',
    '      gap: 12px;',
    '      margin-top: 14px;',
    '    }',
    '    .link-item {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 12px;',
    '      padding: 14px 16px;',
    '      border-radius: 14px;',
    '      background: linear-gradient(180deg, rgba(255,255,255,0.04), rgba(255,255,255,0.02));',
    '      border: 1px solid var(--border);',
    '      text-decoration: none;',
    '      color: var(--text);',
    '      transition: transform 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease;',
    '    }',
    '    .link-item:hover {',
    '      transform: translateY(-2px);',
    '      border-color: #334155;',
    '      box-shadow: 0 10px 25px rgba(0,0,0,0.25);',
    '    }',
    '    .icon {',
    '      width: 28px;',
    '      height: 28px;',
    '      display: grid;',
    '      place-items: center;',
    '      border-radius: 8px;',
    '      background: linear-gradient(135deg, rgba(245,158,11,0.15), rgba(16,185,129,0.12));',
    '      border: 1px solid rgba(255,255,255,0.06);',
    '      font-size: 16px;',
    '    }',
    '    .label {',
    '      font-size: 14px;',
    '      color: var(--muted);',
    '    }',
    '    .value {',
    '      font-size: 14px;',
    '      font-weight: 600;',
    '      color: #f3f4f6;',
    '      word-break: break-word;',
    '    }',
    '    .footer {',
    '      margin-top: 18px;',
    '      text-align: center;',
    '      font-size: 12px;',
    '      color: var(--muted);',
    '    }',
    '    .footer a {',
    '      color: var(--accent-2);',
    '      text-decoration: none;',
    '    }',
    '    .footer a:hover {',
    '      text-decoration: underline;',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="card">',
    '    <div class="header">',
    '      <h1>🙏🏻 Shree Dnyanoba Mauli Tukaram ⛳</h1>',
    '    </div>',
    '    <div class="links">',
    '      <a class="link-item" href="https://www.npmjs.com/~vijay-jadhav1997" target="_blank" rel="noopener">',
    '        <div class="icon">📦</div>',
    '        <div>',
    '          <div class="label">NPM</div>',
    '          <div class="value">My NPM Packages</div>',
    '        </div>',
    '      </a>',
    '      <a class="link-item" href="https://vijay-jadhav1997.netlify.app" target="_blank" rel="noopener">',
    '        <div class="icon">🌐</div>',
    '        <div>',
    '          <div class="label">Website</div>',
    '          <div class="value">Vijay Jadhav</div>',
    '        </div>',
    '      </a>',
    '      <a class="link-item" href="https://www.github.com/vijay-jadhav1997" target="_blank" rel="noopener">',
    '        <div class="icon">🐙</div>',
    '        <div>',
    '          <div class="label">GitHub</div>',
    '          <div class="value">Github - Vijay Jadhav</div>',
    '        </div>',
    '      </a>',
    '      <a class="link-item" href="https://mail.google.com/mail/?view=cm&fs=1&to=vijay.jadhav1997.dev@gmail.com&su=Hello Vijay!" target="_blank" rel="noopener">',
    '        <div class="icon">✉️</div>',
    '        <div>',
    '          <div class="label">Contact Me</div>',
    '          <div class="value">vijay.jadhav1997.dev@gmail.com</div>',
    '        </div>',
    '      </a>',
    '    </div>',
    '    <div class="footer">',
    '      Built with ❤️ using Node + TypeScript',
    '    </div>',
    '  </div>',
    '</body>',
    '</html>',
    '}',
  ]

  return lines.join('\n')
}