
export const packageJsonBoilerplate = (name:string) => {
  const lines = [
    `{`,
    `\t"name": "${name}",`,
    `\t"version": "1.0.0",`,
    `\t"main": "app.js",`,
    `\t"scripts": {`,
    `\t\t"dev": "tsx watch src/app.ts",`,
    `\t\t"build": "tsc",`,
    `\t\t"typecheck": "tsc --noEmit"`,
    `\t},`,
    `\t"keywords": [],`,
    `\t"author": "",`,
    `\t"license": "ISC",`,
    `\t"description": "",`,
    `\t"dependencies": {`,
    `\t\t"dotenv": "^16.6.1",`,
    `\t\t"jsonwebtoken": "^9.0.10",`,
    `\t\t"bcrypt": "^5.1.1",`,
    `\t\t"cookie-parser": "^1.4.10",`,
    `\t\t"moment": "^2.29.4",`,
    `\t\t"uuid": "^9.0.0",`,
    `\t\t"cors": "^2.8.5",`,
    `\t\t"morgan": "^1.10.0",`,
    `\t\t"express": "^4.18.2",`,
    `\t\t"helmet": "^7.0.0",`,
    `\t\t"zod": "^3.22.4",`,
    `\t\t"mongoose": "^8.24.4",`,
    `\t\t"express-rate-limit": "^6.8.0"`,
    `\t},`,
    `\t"devDependencies": {`,
    `\t\t"@types/bcrypt": "^6.0.0",`,
    `\t\t"@types/cors": "^2.8.19",`,
    `\t\t"@types/express": "^5.0.6",`,
    `\t\t"@types/cookie-parser": "^1.4.10",`,
    `\t\t"@types/jsonwebtoken": "^9.0.10",`,
    `\t\t"@types/morgan": "^1.9.10",`,
    `\t\t"typescript": "^7.0.2",`,
    `\t\t"tsx": "^4.23.15"`,
    `\t}`,
    `}`
  ]
  return lines.join("\n")
}

