export const refreshMiddleware = () => {
  const lines = [
    'import { NextFunction, Request, Response } from "express"',
    'import { CatchError, TryError } from "../lib/error"',
    'import AuthModel from "../model/auth.model"',
    'import { SessionInterface, SessionRequestInterface } from "../interface/auth.interface"',
    'import moment from "moment"',
    '',
    'const RefreshTokenMiddleware = async (req:SessionRequestInterface, res: Response, next: NextFunction) => {',
    '\ttry {',
    '\t\tconst refreshToken = req.cookies?.refreshToken',
    '',
    '\t\tif(!refreshToken)',
    '\t\t\tthrow TryError("Refresh token required", 403)',
    '',
    '\t\tconst user = await AuthModel.findOne({refreshToken})',
    '',
    '\t\tif(!user)',
    '\t\t\tthrow TryError("User not found.", 404)',
    '',
    '\t\tconst today = moment()',
    '\t\tconst expiry = moment(user.expiry)',
    '',
    '\t\t if(today.isAfter(expiry))',
    '\t\t\tthrow TryError("refresh token expired", 401)',
    '',
    '\t\t const session: SessionInterface = {',
    '\t\t\tid: user._id,',
    '\t\t\tfullname: user.fullname,',
    '\t\t\temail: user.email,',
    '\t\t\tmobile: user.mobile,',
    '\t\t}',
    '',
    '\t\treq.session = session',
    '\t\tnext()',
    '\t} catch (err) {',
    '\t\t\tCatchError(res, err, "Failed to refresh tokens.")',
    '\t}',
    '}',
    '',
    'export default RefreshTokenMiddleware'
  ]
  return lines.join('\n')
}